spring:
  application:
    name: crypto-mcp-toolkit-client
  profiles:
    active:
    - sse	
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:latest
    mcp:
      client:
        enabled: true
        name: crypto-mcp-toolkit-clinet
        version: 1.1.2
        initialized: true
        annotation-scanner:
          enabled: true
        request-timeout: 30s
        root-change-notification: true
        sse:
          connections:
            server1:
              url: http://localhost:8081
            server2:
              url: http://localhost:8082
        type: async
        toolcallback:
          enabled: true
logging:
  level:
    '[org.springframework.ai]': DEBUG